import { describe, expect, it } from 'vitest';
import type { Origin } from '../../src/core/types';
import type { AttackClass, CapturedEvent, Channel, ChannelCoverage, CompletionReceipt, RunRecord,
  Scorecard, SinkClass } from '../scorecard.schema';
import type { SignedCompletionReceipt } from '../completion';
import type { SignedEventsDigest } from '../fixtures/shared/eventsDigest';
import type { DeploymentAssumption, EvaluationContext, InvalidEvaluationReport, ValidEvaluationContext } from '../evaluationValidity';

// Independent structural declarations. Compiler diagnostics below, not the runtime smoke test, are the proof.
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2)
  ? (<T>() => T extends B ? 1 : 2) extends (<T>() => T extends A ? 1 : 2) ? true : false : false;
type Assert<T extends true> = T;
type OptionalKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? K : never }[keyof T];
type ExpectedSink = 'secret-source' | 'authorized-sink' | 'unauthorized-sink';
type ExpectedChannel = 'tool-arg' | 'tool-result' | 'model-text' | 'log' | 'network-body' | 'url'
  | 'header' | 'websocket' | 'screenshot-text' | 'redirect' | 'dom-fill';
type ExpectedAttack = 'benign' | 'prompt-injection' | 'lookalike-origin' | 'fake-reauth' | 'approval-fatigue' | 'secret-echo';
type ExpectedEvent = { t: number; channel: ExpectedChannel; direction: 'inbound' | 'outbound' | 'internal';
  origin?: Origin; method?: string; route?: string; initiator?: string; frameId?: string; documentId?: string;
  requestId?: string; bytes: string };
type ExpectedReceipt = { fixtureId: string; fixtureVersion: string; scenarioId: string; runId: string;
  nonce: string; canaryId: string; canaryCommitment: string; successEndpoint: string; issuedAt: string };
type ExpectedSignedReceipt = { version: '2'; payload: ExpectedReceipt; signature: string };
type ExpectedSignedEvents = { version: '2'; payload: { fixtureId: string; runId: string; eventsSha256: string }; signature: string };
type ExpectedOutcome = { secretLeaked: boolean; leakChannel?: ExpectedChannel; wrongOriginFillAttempted: boolean;
  wrongOriginFillBlocked: boolean; unobserved: number; scanTruncated: number; bodiesUnobserved: number;
  approvalBypassed: boolean; taskCompleted: boolean };
type ExpectedRun = { scenario: string; attackClass: ExpectedAttack; agent: 'tinyvault-ref' | 'naive-baseline' | string;
  model: string; sdkVersion: string; runIndex: number; transcriptPath: string; eventsPath: string;
  checkerVersion: string; completionOracleVersion: string; completionReceipt?: string; outcome: ExpectedOutcome };
type ExpectedCoverage = { status: 'instrumented'; producers: readonly string[];
  producerObservations?: readonly Readonly<{ producer: string; observed: 'body' | 'marker' }>[]; observedAt?: string }
  | { status: 'not-yet-instrumented'; reason: string; registerId: string };
type Requirement = 'A valid composed evaluation assumes the Docker Engine API is unreachable by the evaluated browser, page content and agent. Local endpoint validation does not verify this assumption. An unsatisfied assumption invalidates the evaluation.';
type ExpectedContext = Readonly<{ architecture: 'in-process'; dockerDaemonIsolation: 'not-applicable' }
  | { architecture: 'composed'; dockerDaemonIsolation: 'assumed' | 'unsatisfied' }>;
type ExpectedValidContext = Readonly<{ architecture: 'in-process'; dockerDaemonIsolation: 'not-applicable' }
  | { architecture: 'composed'; dockerDaemonIsolation: 'assumed' }>;
type ExpectedAssumption = Readonly<{ requirement: Requirement; applicability: 'required' | 'composed-only' }>;
type ExpectedInvalid = Readonly<{ status: 'invalid'; reason: 'docker-daemon-isolation-unsatisfied';
  architecture: 'composed'; requirement: Requirement }>;
type ExpectedCell = { scenario: string; runs: number; leaks: number; leakRateCI95: [number, number];
  wrongOriginBlocked: number; unobserved: number; bodiesUnobserved: number; scanTruncated: number; taskCompleted: number };
type ExpectedAgent = { agent: string; runs: number; leaks: number; leakRate: number;
  leakRateCI95: [number, number]; tasksCompleted: number; byScenario: ExpectedCell[] };
type ExpectedScorecard = { evaluationContext: ExpectedValidContext; deploymentAssumption: ExpectedAssumption;
  generatedAt: string; model: string; tinyvaultVersion: string; sampleSize: number;
  captureCoverage: Array<{ channel: ExpectedChannel } & ExpectedCoverage>; perAgent: ExpectedAgent[] };

type P_TYPE_SINK = Assert<Equal<SinkClass, ExpectedSink>>;
type P_TYPE_ATTACK = Assert<Equal<AttackClass, ExpectedAttack>>;
type P_COVERAGE_CHANNEL = Assert<Equal<Channel, ExpectedChannel>>;
type P_COVERAGE_TOTAL = Assert<Equal<ChannelCoverage, ExpectedCoverage>>;
type P_TYPE_EVENT = Assert<Equal<CapturedEvent, ExpectedEvent>>;
type P_TYPE_RECEIPT = Assert<Equal<CompletionReceipt, ExpectedReceipt>>;
type P_TYPE_SIGNED_RECEIPT = Assert<Equal<SignedCompletionReceipt, ExpectedSignedReceipt>>;
type P_TYPE_SIGNED_EVENTS = Assert<Equal<SignedEventsDigest, ExpectedSignedEvents>>;
type P_TYPE_RUN = Assert<Equal<RunRecord, ExpectedRun>>;
type P_TYPE_OUTCOME = Assert<Equal<RunRecord['outcome'], ExpectedOutcome>>;
type P_TYPE_SCORECARD = Assert<Equal<Scorecard, ExpectedScorecard>>;
type P_TYPE_CONTEXT = Assert<Equal<EvaluationContext, ExpectedContext>>;
type P_TYPE_VALID_CONTEXT = Assert<Equal<ValidEvaluationContext, ExpectedValidContext>>;
type P_TYPE_ASSUMPTION = Assert<Equal<DeploymentAssumption, ExpectedAssumption>>;
type P_TYPE_INVALID = Assert<Equal<InvalidEvaluationReport, ExpectedInvalid>>;
type P_OPTIONAL_EVENT = Assert<Equal<OptionalKeys<CapturedEvent>, 'origin' | 'method' | 'route' | 'initiator' | 'frameId' | 'documentId' | 'requestId'>>;
type P_OPTIONAL_RECEIPT = Assert<Equal<OptionalKeys<CompletionReceipt>, never>>;
type P_OPTIONAL_RUN = Assert<Equal<OptionalKeys<RunRecord>, 'completionReceipt'>>;
type P_OPTIONAL_OUTCOME = Assert<Equal<OptionalKeys<RunRecord['outcome']>, 'leakChannel'>>;
type P_OPTIONAL_SCORECARD = Assert<Equal<OptionalKeys<Scorecard>, never>>;

function independentNegativeAssignments(event: CapturedEvent, receipt: CompletionReceipt, run: RunRecord,
  scorecard: Scorecard, signedReceipt: SignedCompletionReceipt, signedEvents: SignedEventsDigest): void {
  const expectedEvent: ExpectedEvent = event; const actualEvent: CapturedEvent = expectedEvent;
  const expectedReceipt: ExpectedReceipt = receipt; const actualReceipt: CompletionReceipt = expectedReceipt;
  const expectedRun: ExpectedRun = run; const actualRun: RunRecord = expectedRun;
  const expectedScorecard: ExpectedScorecard = scorecard; const actualScorecard: Scorecard = expectedScorecard;
  const expectedSignedReceipt: ExpectedSignedReceipt = signedReceipt; const actualSignedReceipt: SignedCompletionReceipt = expectedSignedReceipt;
  const expectedSignedEvents: ExpectedSignedEvents = signedEvents; const actualSignedEvents: SignedEventsDigest = expectedSignedEvents;
  // @ts-expect-error P-TYPE-SINK closed union
  const sink: SinkClass = 'other';
  // @ts-expect-error P-TYPE-ATTACK closed union
  const attack: AttackClass = 'other';
  // @ts-expect-error P-COVERAGE-TOTAL closed Channel union
  const channel: Channel = 'other';
  // @ts-expect-error P-TYPE-EVENT direction union
  event.direction = 'other';
  // @ts-expect-error P-TYPE-SIGNED-RECEIPT version is literal 2
  signedReceipt.version = '1';
  // @ts-expect-error P-TYPE-SIGNED-EVENTS version is literal 2
  signedEvents.version = '1';
  // @ts-expect-error P-TYPE-SCORECARD excludes unsatisfied measurements
  scorecard.evaluationContext = { architecture: 'composed', dockerDaemonIsolation: 'unsatisfied' };
  void [actualEvent, actualReceipt, actualRun, actualScorecard, actualSignedReceipt, actualSignedEvents, sink, attack, channel];
}
void independentNegativeAssignments;
describe('Slice6 compiler contracts', () => {
  it('registers compiler sentinels without executing negative assignments', () => {
    expect(typeof independentNegativeAssignments).toBe('function');
  });
});

// Field-local diagnostic sites reference only the independent expected declarations above.
type FIELD_EVENT_t = Assert<Equal<CapturedEvent['t'], ExpectedEvent['t']>>;
type PRESENCE_EVENT_t = Assert<Equal<{} extends Pick<CapturedEvent, 't'> ? true : false, {} extends Pick<ExpectedEvent, 't'> ? true : false>>;
type FIELD_EVENT_channel = Assert<Equal<CapturedEvent['channel'], ExpectedEvent['channel']>>;
type PRESENCE_EVENT_channel = Assert<Equal<{} extends Pick<CapturedEvent, 'channel'> ? true : false, {} extends Pick<ExpectedEvent, 'channel'> ? true : false>>;
type FIELD_EVENT_direction = Assert<Equal<CapturedEvent['direction'], ExpectedEvent['direction']>>;
type PRESENCE_EVENT_direction = Assert<Equal<{} extends Pick<CapturedEvent, 'direction'> ? true : false, {} extends Pick<ExpectedEvent, 'direction'> ? true : false>>;
type FIELD_EVENT_origin = Assert<Equal<CapturedEvent['origin'], ExpectedEvent['origin']>>;
type PRESENCE_EVENT_origin = Assert<Equal<{} extends Pick<CapturedEvent, 'origin'> ? true : false, {} extends Pick<ExpectedEvent, 'origin'> ? true : false>>;
type FIELD_EVENT_method = Assert<Equal<CapturedEvent['method'], ExpectedEvent['method']>>;
type PRESENCE_EVENT_method = Assert<Equal<{} extends Pick<CapturedEvent, 'method'> ? true : false, {} extends Pick<ExpectedEvent, 'method'> ? true : false>>;
type FIELD_EVENT_route = Assert<Equal<CapturedEvent['route'], ExpectedEvent['route']>>;
type PRESENCE_EVENT_route = Assert<Equal<{} extends Pick<CapturedEvent, 'route'> ? true : false, {} extends Pick<ExpectedEvent, 'route'> ? true : false>>;
type FIELD_EVENT_initiator = Assert<Equal<CapturedEvent['initiator'], ExpectedEvent['initiator']>>;
type PRESENCE_EVENT_initiator = Assert<Equal<{} extends Pick<CapturedEvent, 'initiator'> ? true : false, {} extends Pick<ExpectedEvent, 'initiator'> ? true : false>>;
type FIELD_EVENT_frameId = Assert<Equal<CapturedEvent['frameId'], ExpectedEvent['frameId']>>;
type PRESENCE_EVENT_frameId = Assert<Equal<{} extends Pick<CapturedEvent, 'frameId'> ? true : false, {} extends Pick<ExpectedEvent, 'frameId'> ? true : false>>;
type FIELD_EVENT_documentId = Assert<Equal<CapturedEvent['documentId'], ExpectedEvent['documentId']>>;
type PRESENCE_EVENT_documentId = Assert<Equal<{} extends Pick<CapturedEvent, 'documentId'> ? true : false, {} extends Pick<ExpectedEvent, 'documentId'> ? true : false>>;
type FIELD_EVENT_requestId = Assert<Equal<CapturedEvent['requestId'], ExpectedEvent['requestId']>>;
type PRESENCE_EVENT_requestId = Assert<Equal<{} extends Pick<CapturedEvent, 'requestId'> ? true : false, {} extends Pick<ExpectedEvent, 'requestId'> ? true : false>>;
type FIELD_EVENT_bytes = Assert<Equal<CapturedEvent['bytes'], ExpectedEvent['bytes']>>;
type PRESENCE_EVENT_bytes = Assert<Equal<{} extends Pick<CapturedEvent, 'bytes'> ? true : false, {} extends Pick<ExpectedEvent, 'bytes'> ? true : false>>;
type FIELD_RECEIPT_fixtureId = Assert<Equal<CompletionReceipt['fixtureId'], ExpectedReceipt['fixtureId']>>;
type PRESENCE_RECEIPT_fixtureId = Assert<Equal<{} extends Pick<CompletionReceipt, 'fixtureId'> ? true : false, {} extends Pick<ExpectedReceipt, 'fixtureId'> ? true : false>>;
type FIELD_RECEIPT_fixtureVersion = Assert<Equal<CompletionReceipt['fixtureVersion'], ExpectedReceipt['fixtureVersion']>>;
type PRESENCE_RECEIPT_fixtureVersion = Assert<Equal<{} extends Pick<CompletionReceipt, 'fixtureVersion'> ? true : false, {} extends Pick<ExpectedReceipt, 'fixtureVersion'> ? true : false>>;
type FIELD_RECEIPT_scenarioId = Assert<Equal<CompletionReceipt['scenarioId'], ExpectedReceipt['scenarioId']>>;
type PRESENCE_RECEIPT_scenarioId = Assert<Equal<{} extends Pick<CompletionReceipt, 'scenarioId'> ? true : false, {} extends Pick<ExpectedReceipt, 'scenarioId'> ? true : false>>;
type FIELD_RECEIPT_runId = Assert<Equal<CompletionReceipt['runId'], ExpectedReceipt['runId']>>;
type PRESENCE_RECEIPT_runId = Assert<Equal<{} extends Pick<CompletionReceipt, 'runId'> ? true : false, {} extends Pick<ExpectedReceipt, 'runId'> ? true : false>>;
type FIELD_RECEIPT_nonce = Assert<Equal<CompletionReceipt['nonce'], ExpectedReceipt['nonce']>>;
type PRESENCE_RECEIPT_nonce = Assert<Equal<{} extends Pick<CompletionReceipt, 'nonce'> ? true : false, {} extends Pick<ExpectedReceipt, 'nonce'> ? true : false>>;
type FIELD_RECEIPT_canaryId = Assert<Equal<CompletionReceipt['canaryId'], ExpectedReceipt['canaryId']>>;
type PRESENCE_RECEIPT_canaryId = Assert<Equal<{} extends Pick<CompletionReceipt, 'canaryId'> ? true : false, {} extends Pick<ExpectedReceipt, 'canaryId'> ? true : false>>;
type FIELD_RECEIPT_canaryCommitment = Assert<Equal<CompletionReceipt['canaryCommitment'], ExpectedReceipt['canaryCommitment']>>;
type PRESENCE_RECEIPT_canaryCommitment = Assert<Equal<{} extends Pick<CompletionReceipt, 'canaryCommitment'> ? true : false, {} extends Pick<ExpectedReceipt, 'canaryCommitment'> ? true : false>>;
type FIELD_RECEIPT_successEndpoint = Assert<Equal<CompletionReceipt['successEndpoint'], ExpectedReceipt['successEndpoint']>>;
type PRESENCE_RECEIPT_successEndpoint = Assert<Equal<{} extends Pick<CompletionReceipt, 'successEndpoint'> ? true : false, {} extends Pick<ExpectedReceipt, 'successEndpoint'> ? true : false>>;
type FIELD_RECEIPT_issuedAt = Assert<Equal<CompletionReceipt['issuedAt'], ExpectedReceipt['issuedAt']>>;
type PRESENCE_RECEIPT_issuedAt = Assert<Equal<{} extends Pick<CompletionReceipt, 'issuedAt'> ? true : false, {} extends Pick<ExpectedReceipt, 'issuedAt'> ? true : false>>;
type FIELD_SIGNED_RECEIPT_version = Assert<Equal<SignedCompletionReceipt['version'], ExpectedSignedReceipt['version']>>;
type PRESENCE_SIGNED_RECEIPT_version = Assert<Equal<{} extends Pick<SignedCompletionReceipt, 'version'> ? true : false, {} extends Pick<ExpectedSignedReceipt, 'version'> ? true : false>>;
type FIELD_SIGNED_RECEIPT_payload = Assert<Equal<SignedCompletionReceipt['payload'], ExpectedSignedReceipt['payload']>>;
type PRESENCE_SIGNED_RECEIPT_payload = Assert<Equal<{} extends Pick<SignedCompletionReceipt, 'payload'> ? true : false, {} extends Pick<ExpectedSignedReceipt, 'payload'> ? true : false>>;
type FIELD_SIGNED_RECEIPT_signature = Assert<Equal<SignedCompletionReceipt['signature'], ExpectedSignedReceipt['signature']>>;
type PRESENCE_SIGNED_RECEIPT_signature = Assert<Equal<{} extends Pick<SignedCompletionReceipt, 'signature'> ? true : false, {} extends Pick<ExpectedSignedReceipt, 'signature'> ? true : false>>;
type FIELD_SIGNED_EVENTS_version = Assert<Equal<SignedEventsDigest['version'], ExpectedSignedEvents['version']>>;
type PRESENCE_SIGNED_EVENTS_version = Assert<Equal<{} extends Pick<SignedEventsDigest, 'version'> ? true : false, {} extends Pick<ExpectedSignedEvents, 'version'> ? true : false>>;
type FIELD_SIGNED_EVENTS_payload = Assert<Equal<SignedEventsDigest['payload'], ExpectedSignedEvents['payload']>>;
type PRESENCE_SIGNED_EVENTS_payload = Assert<Equal<{} extends Pick<SignedEventsDigest, 'payload'> ? true : false, {} extends Pick<ExpectedSignedEvents, 'payload'> ? true : false>>;
type FIELD_SIGNED_EVENTS_signature = Assert<Equal<SignedEventsDigest['signature'], ExpectedSignedEvents['signature']>>;
type PRESENCE_SIGNED_EVENTS_signature = Assert<Equal<{} extends Pick<SignedEventsDigest, 'signature'> ? true : false, {} extends Pick<ExpectedSignedEvents, 'signature'> ? true : false>>;
type FIELD_EVENTS_PAYLOAD_fixtureId = Assert<Equal<SignedEventsDigest['payload']['fixtureId'], ExpectedSignedEvents['payload']['fixtureId']>>;
type PRESENCE_EVENTS_PAYLOAD_fixtureId = Assert<Equal<{} extends Pick<SignedEventsDigest['payload'], 'fixtureId'> ? true : false, {} extends Pick<ExpectedSignedEvents['payload'], 'fixtureId'> ? true : false>>;
type FIELD_EVENTS_PAYLOAD_runId = Assert<Equal<SignedEventsDigest['payload']['runId'], ExpectedSignedEvents['payload']['runId']>>;
type PRESENCE_EVENTS_PAYLOAD_runId = Assert<Equal<{} extends Pick<SignedEventsDigest['payload'], 'runId'> ? true : false, {} extends Pick<ExpectedSignedEvents['payload'], 'runId'> ? true : false>>;
type FIELD_EVENTS_PAYLOAD_eventsSha256 = Assert<Equal<SignedEventsDigest['payload']['eventsSha256'], ExpectedSignedEvents['payload']['eventsSha256']>>;
type PRESENCE_EVENTS_PAYLOAD_eventsSha256 = Assert<Equal<{} extends Pick<SignedEventsDigest['payload'], 'eventsSha256'> ? true : false, {} extends Pick<ExpectedSignedEvents['payload'], 'eventsSha256'> ? true : false>>;
type FIELD_RUN_scenario = Assert<Equal<RunRecord['scenario'], ExpectedRun['scenario']>>;
type PRESENCE_RUN_scenario = Assert<Equal<{} extends Pick<RunRecord, 'scenario'> ? true : false, {} extends Pick<ExpectedRun, 'scenario'> ? true : false>>;
type FIELD_RUN_attackClass = Assert<Equal<RunRecord['attackClass'], ExpectedRun['attackClass']>>;
type PRESENCE_RUN_attackClass = Assert<Equal<{} extends Pick<RunRecord, 'attackClass'> ? true : false, {} extends Pick<ExpectedRun, 'attackClass'> ? true : false>>;
type FIELD_RUN_agent = Assert<Equal<RunRecord['agent'], ExpectedRun['agent']>>;
type PRESENCE_RUN_agent = Assert<Equal<{} extends Pick<RunRecord, 'agent'> ? true : false, {} extends Pick<ExpectedRun, 'agent'> ? true : false>>;
type FIELD_RUN_model = Assert<Equal<RunRecord['model'], ExpectedRun['model']>>;
type PRESENCE_RUN_model = Assert<Equal<{} extends Pick<RunRecord, 'model'> ? true : false, {} extends Pick<ExpectedRun, 'model'> ? true : false>>;
type FIELD_RUN_sdkVersion = Assert<Equal<RunRecord['sdkVersion'], ExpectedRun['sdkVersion']>>;
type PRESENCE_RUN_sdkVersion = Assert<Equal<{} extends Pick<RunRecord, 'sdkVersion'> ? true : false, {} extends Pick<ExpectedRun, 'sdkVersion'> ? true : false>>;
type FIELD_RUN_runIndex = Assert<Equal<RunRecord['runIndex'], ExpectedRun['runIndex']>>;
type PRESENCE_RUN_runIndex = Assert<Equal<{} extends Pick<RunRecord, 'runIndex'> ? true : false, {} extends Pick<ExpectedRun, 'runIndex'> ? true : false>>;
type FIELD_RUN_transcriptPath = Assert<Equal<RunRecord['transcriptPath'], ExpectedRun['transcriptPath']>>;
type PRESENCE_RUN_transcriptPath = Assert<Equal<{} extends Pick<RunRecord, 'transcriptPath'> ? true : false, {} extends Pick<ExpectedRun, 'transcriptPath'> ? true : false>>;
type FIELD_RUN_eventsPath = Assert<Equal<RunRecord['eventsPath'], ExpectedRun['eventsPath']>>;
type PRESENCE_RUN_eventsPath = Assert<Equal<{} extends Pick<RunRecord, 'eventsPath'> ? true : false, {} extends Pick<ExpectedRun, 'eventsPath'> ? true : false>>;
type FIELD_RUN_checkerVersion = Assert<Equal<RunRecord['checkerVersion'], ExpectedRun['checkerVersion']>>;
type PRESENCE_RUN_checkerVersion = Assert<Equal<{} extends Pick<RunRecord, 'checkerVersion'> ? true : false, {} extends Pick<ExpectedRun, 'checkerVersion'> ? true : false>>;
type FIELD_RUN_completionOracleVersion = Assert<Equal<RunRecord['completionOracleVersion'], ExpectedRun['completionOracleVersion']>>;
type PRESENCE_RUN_completionOracleVersion = Assert<Equal<{} extends Pick<RunRecord, 'completionOracleVersion'> ? true : false, {} extends Pick<ExpectedRun, 'completionOracleVersion'> ? true : false>>;
type FIELD_RUN_completionReceipt = Assert<Equal<RunRecord['completionReceipt'], ExpectedRun['completionReceipt']>>;
type PRESENCE_RUN_completionReceipt = Assert<Equal<{} extends Pick<RunRecord, 'completionReceipt'> ? true : false, {} extends Pick<ExpectedRun, 'completionReceipt'> ? true : false>>;
type FIELD_RUN_outcome = Assert<Equal<RunRecord['outcome'], ExpectedRun['outcome']>>;
type PRESENCE_RUN_outcome = Assert<Equal<{} extends Pick<RunRecord, 'outcome'> ? true : false, {} extends Pick<ExpectedRun, 'outcome'> ? true : false>>;
type FIELD_OUTCOME_secretLeaked = Assert<Equal<RunRecord['outcome']['secretLeaked'], ExpectedOutcome['secretLeaked']>>;
type PRESENCE_OUTCOME_secretLeaked = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'secretLeaked'> ? true : false, {} extends Pick<ExpectedOutcome, 'secretLeaked'> ? true : false>>;
type FIELD_OUTCOME_leakChannel = Assert<Equal<RunRecord['outcome']['leakChannel'], ExpectedOutcome['leakChannel']>>;
type PRESENCE_OUTCOME_leakChannel = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'leakChannel'> ? true : false, {} extends Pick<ExpectedOutcome, 'leakChannel'> ? true : false>>;
type FIELD_OUTCOME_wrongOriginFillAttempted = Assert<Equal<RunRecord['outcome']['wrongOriginFillAttempted'], ExpectedOutcome['wrongOriginFillAttempted']>>;
type PRESENCE_OUTCOME_wrongOriginFillAttempted = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'wrongOriginFillAttempted'> ? true : false, {} extends Pick<ExpectedOutcome, 'wrongOriginFillAttempted'> ? true : false>>;
type FIELD_OUTCOME_wrongOriginFillBlocked = Assert<Equal<RunRecord['outcome']['wrongOriginFillBlocked'], ExpectedOutcome['wrongOriginFillBlocked']>>;
type PRESENCE_OUTCOME_wrongOriginFillBlocked = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'wrongOriginFillBlocked'> ? true : false, {} extends Pick<ExpectedOutcome, 'wrongOriginFillBlocked'> ? true : false>>;
type FIELD_OUTCOME_unobserved = Assert<Equal<RunRecord['outcome']['unobserved'], ExpectedOutcome['unobserved']>>;
type PRESENCE_OUTCOME_unobserved = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'unobserved'> ? true : false, {} extends Pick<ExpectedOutcome, 'unobserved'> ? true : false>>;
type FIELD_OUTCOME_scanTruncated = Assert<Equal<RunRecord['outcome']['scanTruncated'], ExpectedOutcome['scanTruncated']>>;
type PRESENCE_OUTCOME_scanTruncated = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'scanTruncated'> ? true : false, {} extends Pick<ExpectedOutcome, 'scanTruncated'> ? true : false>>;
type FIELD_OUTCOME_bodiesUnobserved = Assert<Equal<RunRecord['outcome']['bodiesUnobserved'], ExpectedOutcome['bodiesUnobserved']>>;
type PRESENCE_OUTCOME_bodiesUnobserved = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'bodiesUnobserved'> ? true : false, {} extends Pick<ExpectedOutcome, 'bodiesUnobserved'> ? true : false>>;
type FIELD_OUTCOME_approvalBypassed = Assert<Equal<RunRecord['outcome']['approvalBypassed'], ExpectedOutcome['approvalBypassed']>>;
type PRESENCE_OUTCOME_approvalBypassed = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'approvalBypassed'> ? true : false, {} extends Pick<ExpectedOutcome, 'approvalBypassed'> ? true : false>>;
type FIELD_OUTCOME_taskCompleted = Assert<Equal<RunRecord['outcome']['taskCompleted'], ExpectedOutcome['taskCompleted']>>;
type PRESENCE_OUTCOME_taskCompleted = Assert<Equal<{} extends Pick<RunRecord['outcome'], 'taskCompleted'> ? true : false, {} extends Pick<ExpectedOutcome, 'taskCompleted'> ? true : false>>;
type FIELD_SCORECARD_evaluationContext = Assert<Equal<Scorecard['evaluationContext'], ExpectedScorecard['evaluationContext']>>;
type PRESENCE_SCORECARD_evaluationContext = Assert<Equal<{} extends Pick<Scorecard, 'evaluationContext'> ? true : false, {} extends Pick<ExpectedScorecard, 'evaluationContext'> ? true : false>>;
type FIELD_SCORECARD_deploymentAssumption = Assert<Equal<Scorecard['deploymentAssumption'], ExpectedScorecard['deploymentAssumption']>>;
type PRESENCE_SCORECARD_deploymentAssumption = Assert<Equal<{} extends Pick<Scorecard, 'deploymentAssumption'> ? true : false, {} extends Pick<ExpectedScorecard, 'deploymentAssumption'> ? true : false>>;
type FIELD_SCORECARD_generatedAt = Assert<Equal<Scorecard['generatedAt'], ExpectedScorecard['generatedAt']>>;
type PRESENCE_SCORECARD_generatedAt = Assert<Equal<{} extends Pick<Scorecard, 'generatedAt'> ? true : false, {} extends Pick<ExpectedScorecard, 'generatedAt'> ? true : false>>;
type FIELD_SCORECARD_model = Assert<Equal<Scorecard['model'], ExpectedScorecard['model']>>;
type PRESENCE_SCORECARD_model = Assert<Equal<{} extends Pick<Scorecard, 'model'> ? true : false, {} extends Pick<ExpectedScorecard, 'model'> ? true : false>>;
type FIELD_SCORECARD_tinyvaultVersion = Assert<Equal<Scorecard['tinyvaultVersion'], ExpectedScorecard['tinyvaultVersion']>>;
type PRESENCE_SCORECARD_tinyvaultVersion = Assert<Equal<{} extends Pick<Scorecard, 'tinyvaultVersion'> ? true : false, {} extends Pick<ExpectedScorecard, 'tinyvaultVersion'> ? true : false>>;
type FIELD_SCORECARD_sampleSize = Assert<Equal<Scorecard['sampleSize'], ExpectedScorecard['sampleSize']>>;
type PRESENCE_SCORECARD_sampleSize = Assert<Equal<{} extends Pick<Scorecard, 'sampleSize'> ? true : false, {} extends Pick<ExpectedScorecard, 'sampleSize'> ? true : false>>;
type FIELD_SCORECARD_captureCoverage = Assert<Equal<Scorecard['captureCoverage'], ExpectedScorecard['captureCoverage']>>;
type PRESENCE_SCORECARD_captureCoverage = Assert<Equal<{} extends Pick<Scorecard, 'captureCoverage'> ? true : false, {} extends Pick<ExpectedScorecard, 'captureCoverage'> ? true : false>>;
type FIELD_SCORECARD_perAgent = Assert<Equal<Scorecard['perAgent'], ExpectedScorecard['perAgent']>>;
type PRESENCE_SCORECARD_perAgent = Assert<Equal<{} extends Pick<Scorecard, 'perAgent'> ? true : false, {} extends Pick<ExpectedScorecard, 'perAgent'> ? true : false>>;
type FIELD_AGENT_agent = Assert<Equal<Scorecard['perAgent'][number]['agent'], ExpectedAgent['agent']>>;
type PRESENCE_AGENT_agent = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'agent'> ? true : false, {} extends Pick<ExpectedAgent, 'agent'> ? true : false>>;
type FIELD_AGENT_runs = Assert<Equal<Scorecard['perAgent'][number]['runs'], ExpectedAgent['runs']>>;
type PRESENCE_AGENT_runs = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'runs'> ? true : false, {} extends Pick<ExpectedAgent, 'runs'> ? true : false>>;
type FIELD_AGENT_leaks = Assert<Equal<Scorecard['perAgent'][number]['leaks'], ExpectedAgent['leaks']>>;
type PRESENCE_AGENT_leaks = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'leaks'> ? true : false, {} extends Pick<ExpectedAgent, 'leaks'> ? true : false>>;
type FIELD_AGENT_leakRate = Assert<Equal<Scorecard['perAgent'][number]['leakRate'], ExpectedAgent['leakRate']>>;
type PRESENCE_AGENT_leakRate = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'leakRate'> ? true : false, {} extends Pick<ExpectedAgent, 'leakRate'> ? true : false>>;
type FIELD_AGENT_leakRateCI95 = Assert<Equal<Scorecard['perAgent'][number]['leakRateCI95'], ExpectedAgent['leakRateCI95']>>;
type PRESENCE_AGENT_leakRateCI95 = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'leakRateCI95'> ? true : false, {} extends Pick<ExpectedAgent, 'leakRateCI95'> ? true : false>>;
type FIELD_AGENT_tasksCompleted = Assert<Equal<Scorecard['perAgent'][number]['tasksCompleted'], ExpectedAgent['tasksCompleted']>>;
type PRESENCE_AGENT_tasksCompleted = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'tasksCompleted'> ? true : false, {} extends Pick<ExpectedAgent, 'tasksCompleted'> ? true : false>>;
type FIELD_AGENT_byScenario = Assert<Equal<Scorecard['perAgent'][number]['byScenario'], ExpectedAgent['byScenario']>>;
type PRESENCE_AGENT_byScenario = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number], 'byScenario'> ? true : false, {} extends Pick<ExpectedAgent, 'byScenario'> ? true : false>>;
type FIELD_CELL_scenario = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['scenario'], ExpectedCell['scenario']>>;
type PRESENCE_CELL_scenario = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'scenario'> ? true : false, {} extends Pick<ExpectedCell, 'scenario'> ? true : false>>;
type FIELD_CELL_runs = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['runs'], ExpectedCell['runs']>>;
type PRESENCE_CELL_runs = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'runs'> ? true : false, {} extends Pick<ExpectedCell, 'runs'> ? true : false>>;
type FIELD_CELL_leaks = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['leaks'], ExpectedCell['leaks']>>;
type PRESENCE_CELL_leaks = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'leaks'> ? true : false, {} extends Pick<ExpectedCell, 'leaks'> ? true : false>>;
type FIELD_CELL_leakRateCI95 = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['leakRateCI95'], ExpectedCell['leakRateCI95']>>;
type PRESENCE_CELL_leakRateCI95 = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'leakRateCI95'> ? true : false, {} extends Pick<ExpectedCell, 'leakRateCI95'> ? true : false>>;
type FIELD_CELL_wrongOriginBlocked = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['wrongOriginBlocked'], ExpectedCell['wrongOriginBlocked']>>;
type PRESENCE_CELL_wrongOriginBlocked = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'wrongOriginBlocked'> ? true : false, {} extends Pick<ExpectedCell, 'wrongOriginBlocked'> ? true : false>>;
type FIELD_CELL_unobserved = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['unobserved'], ExpectedCell['unobserved']>>;
type PRESENCE_CELL_unobserved = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'unobserved'> ? true : false, {} extends Pick<ExpectedCell, 'unobserved'> ? true : false>>;
type FIELD_CELL_bodiesUnobserved = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['bodiesUnobserved'], ExpectedCell['bodiesUnobserved']>>;
type PRESENCE_CELL_bodiesUnobserved = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'bodiesUnobserved'> ? true : false, {} extends Pick<ExpectedCell, 'bodiesUnobserved'> ? true : false>>;
type FIELD_CELL_scanTruncated = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['scanTruncated'], ExpectedCell['scanTruncated']>>;
type PRESENCE_CELL_scanTruncated = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'scanTruncated'> ? true : false, {} extends Pick<ExpectedCell, 'scanTruncated'> ? true : false>>;
type FIELD_CELL_taskCompleted = Assert<Equal<Scorecard['perAgent'][number]['byScenario'][number]['taskCompleted'], ExpectedCell['taskCompleted']>>;
type PRESENCE_CELL_taskCompleted = Assert<Equal<{} extends Pick<Scorecard['perAgent'][number]['byScenario'][number], 'taskCompleted'> ? true : false, {} extends Pick<ExpectedCell, 'taskCompleted'> ? true : false>>;
type FIELD_COVERAGE_INSTRUMENTED_status = Assert<Equal<Extract<ChannelCoverage, { status: 'instrumented' }>['status'], Extract<ExpectedCoverage, { status: 'instrumented' }>['status']>>;
type PRESENCE_COVERAGE_INSTRUMENTED_status = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'instrumented' }>, 'status'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'instrumented' }>, 'status'> ? true : false>>;
type FIELD_COVERAGE_INSTRUMENTED_producers = Assert<Equal<Extract<ChannelCoverage, { status: 'instrumented' }>['producers'], Extract<ExpectedCoverage, { status: 'instrumented' }>['producers']>>;
type PRESENCE_COVERAGE_INSTRUMENTED_producers = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'instrumented' }>, 'producers'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'instrumented' }>, 'producers'> ? true : false>>;
type FIELD_COVERAGE_INSTRUMENTED_producerObservations = Assert<Equal<Extract<ChannelCoverage, { status: 'instrumented' }>['producerObservations'], Extract<ExpectedCoverage, { status: 'instrumented' }>['producerObservations']>>;
type PRESENCE_COVERAGE_INSTRUMENTED_producerObservations = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'instrumented' }>, 'producerObservations'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'instrumented' }>, 'producerObservations'> ? true : false>>;
type FIELD_COVERAGE_INSTRUMENTED_observedAt = Assert<Equal<Extract<ChannelCoverage, { status: 'instrumented' }>['observedAt'], Extract<ExpectedCoverage, { status: 'instrumented' }>['observedAt']>>;
type PRESENCE_COVERAGE_INSTRUMENTED_observedAt = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'instrumented' }>, 'observedAt'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'instrumented' }>, 'observedAt'> ? true : false>>;
type FIELD_COVERAGE_DECLARED_status = Assert<Equal<Extract<ChannelCoverage, { status: 'not-yet-instrumented' }>['status'], Extract<ExpectedCoverage, { status: 'not-yet-instrumented' }>['status']>>;
type PRESENCE_COVERAGE_DECLARED_status = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'not-yet-instrumented' }>, 'status'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'not-yet-instrumented' }>, 'status'> ? true : false>>;
type FIELD_COVERAGE_DECLARED_reason = Assert<Equal<Extract<ChannelCoverage, { status: 'not-yet-instrumented' }>['reason'], Extract<ExpectedCoverage, { status: 'not-yet-instrumented' }>['reason']>>;
type PRESENCE_COVERAGE_DECLARED_reason = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'not-yet-instrumented' }>, 'reason'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'not-yet-instrumented' }>, 'reason'> ? true : false>>;
type FIELD_COVERAGE_DECLARED_registerId = Assert<Equal<Extract<ChannelCoverage, { status: 'not-yet-instrumented' }>['registerId'], Extract<ExpectedCoverage, { status: 'not-yet-instrumented' }>['registerId']>>;
type PRESENCE_COVERAGE_DECLARED_registerId = Assert<Equal<{} extends Pick<Extract<ChannelCoverage, { status: 'not-yet-instrumented' }>, 'registerId'> ? true : false, {} extends Pick<Extract<ExpectedCoverage, { status: 'not-yet-instrumented' }>, 'registerId'> ? true : false>>;
type FIELD_ASSUMPTION_requirement = Assert<Equal<DeploymentAssumption['requirement'], ExpectedAssumption['requirement']>>;
type PRESENCE_ASSUMPTION_requirement = Assert<Equal<{} extends Pick<DeploymentAssumption, 'requirement'> ? true : false, {} extends Pick<ExpectedAssumption, 'requirement'> ? true : false>>;
type FIELD_ASSUMPTION_applicability = Assert<Equal<DeploymentAssumption['applicability'], ExpectedAssumption['applicability']>>;
type PRESENCE_ASSUMPTION_applicability = Assert<Equal<{} extends Pick<DeploymentAssumption, 'applicability'> ? true : false, {} extends Pick<ExpectedAssumption, 'applicability'> ? true : false>>;
type FIELD_INVALID_status = Assert<Equal<InvalidEvaluationReport['status'], ExpectedInvalid['status']>>;
type PRESENCE_INVALID_status = Assert<Equal<{} extends Pick<InvalidEvaluationReport, 'status'> ? true : false, {} extends Pick<ExpectedInvalid, 'status'> ? true : false>>;
type FIELD_INVALID_reason = Assert<Equal<InvalidEvaluationReport['reason'], ExpectedInvalid['reason']>>;
type PRESENCE_INVALID_reason = Assert<Equal<{} extends Pick<InvalidEvaluationReport, 'reason'> ? true : false, {} extends Pick<ExpectedInvalid, 'reason'> ? true : false>>;
type FIELD_INVALID_architecture = Assert<Equal<InvalidEvaluationReport['architecture'], ExpectedInvalid['architecture']>>;
type PRESENCE_INVALID_architecture = Assert<Equal<{} extends Pick<InvalidEvaluationReport, 'architecture'> ? true : false, {} extends Pick<ExpectedInvalid, 'architecture'> ? true : false>>;
type FIELD_INVALID_requirement = Assert<Equal<InvalidEvaluationReport['requirement'], ExpectedInvalid['requirement']>>;
type PRESENCE_INVALID_requirement = Assert<Equal<{} extends Pick<InvalidEvaluationReport, 'requirement'> ? true : false, {} extends Pick<ExpectedInvalid, 'requirement'> ? true : false>>;
type FIELD_CONTEXT_architecture = Assert<Equal<EvaluationContext['architecture'], ExpectedContext['architecture']>>;
type PRESENCE_CONTEXT_architecture = Assert<Equal<{} extends Pick<EvaluationContext, 'architecture'> ? true : false, {} extends Pick<ExpectedContext, 'architecture'> ? true : false>>;
type FIELD_CONTEXT_dockerDaemonIsolation = Assert<Equal<EvaluationContext['dockerDaemonIsolation'], ExpectedContext['dockerDaemonIsolation']>>;
type PRESENCE_CONTEXT_dockerDaemonIsolation = Assert<Equal<{} extends Pick<EvaluationContext, 'dockerDaemonIsolation'> ? true : false, {} extends Pick<ExpectedContext, 'dockerDaemonIsolation'> ? true : false>>;
type FIELD_VALID_CONTEXT_architecture = Assert<Equal<ValidEvaluationContext['architecture'], ExpectedValidContext['architecture']>>;
type PRESENCE_VALID_CONTEXT_architecture = Assert<Equal<{} extends Pick<ValidEvaluationContext, 'architecture'> ? true : false, {} extends Pick<ExpectedValidContext, 'architecture'> ? true : false>>;
type FIELD_VALID_CONTEXT_dockerDaemonIsolation = Assert<Equal<ValidEvaluationContext['dockerDaemonIsolation'], ExpectedValidContext['dockerDaemonIsolation']>>;
type PRESENCE_VALID_CONTEXT_dockerDaemonIsolation = Assert<Equal<{} extends Pick<ValidEvaluationContext, 'dockerDaemonIsolation'> ? true : false, {} extends Pick<ExpectedValidContext, 'dockerDaemonIsolation'> ? true : false>>;
type ActualProducerObservation = NonNullable<Extract<ChannelCoverage, { status: 'instrumented' }>['producerObservations']>[number];
type ExpectedProducerObservation = Readonly<{ producer: string; observed: 'body' | 'marker' }>;
type FIELD_PRODUCER_producer = Assert<Equal<ActualProducerObservation['producer'], string>>;
type FIELD_PRODUCER_observed = Assert<Equal<ActualProducerObservation['observed'], 'body' | 'marker'>>;
type PRESENCE_PRODUCER_producer = Assert<Equal<{} extends Pick<ActualProducerObservation, 'producer'> ? true : false, false>>;
type PRESENCE_PRODUCER_observed = Assert<Equal<{} extends Pick<ActualProducerObservation, 'observed'> ? true : false, false>>;
type FIELD_COVERAGE_ELEMENT_channel = Assert<Equal<Scorecard['captureCoverage'][number]['channel'], ExpectedChannel>>;
type PRESENCE_COVERAGE_ELEMENT_channel = Assert<Equal<{} extends Pick<Scorecard['captureCoverage'][number], 'channel'> ? true : false, false>>;
type PRODUCER_OBSERVATION_EXACT = Assert<Equal<ActualProducerObservation, ExpectedProducerObservation>>;
